//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsLibrary.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicsLibrary.Data.StoredProcedures", typeof(StoredProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[DeleteSeries]
        ///    @SeriesId INT
        ///AS
        ///BEGIN
        ///
        ///	DELETE FROM [ComicsLibrary].[HomeBookTypes]
        ///	WHERE [SeriesId] = @SeriesId
        ///
        ///	DELETE FROM [ComicsLibrary].[Books]
        ///	WHERE [SeriesId] = @SeriesId
        ///
        ///	DELETE FROM [ComicsLibrary].[Series]
        ///	WHERE [Id] = @SeriesId
        ///
        ///END
        ///GO.
        /// </summary>
        internal static string Create_DeleteSeries {
            get {
                return ResourceManager.GetString("Create_DeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetAllSeries]
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		S.Id,
        ///        S.Title,
        ///        B.ImageUrl,
        ///        (SELECT COUNT([BookId]) FROM [ComicsLibrary].[SeriesUnreadBooks] WHERE [SeriesId] = S.[Id]) UnreadBooks,
        ///        (SELECT COUNT([BookId]) FROM [ComicsLibrary].[SeriesAllBooks] WHERE [SeriesId] = S.[Id]) TotalBooks,
        ///        S.SourceID,
        ///        SRC.[Name] SourceName,
        ///        [StartYear],
        ///        [EndYear],
        ///        [LastUpdated],
        ///        [Abandoned] [Archived],
        ///        S.[Sourc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetAllSeries {
            get {
                return ResourceManager.GetString("Create_GetAllSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetAllSeries]
        ///    @SeriesID INT = NULL
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		S.Id,
        ///        S.Title,
        ///        B.ImageUrl,
        ///        (SELECT COUNT([BookId]) FROM [ComicsLibrary].[SeriesUnreadBooks] WHERE [SeriesId] = S.[Id]) UnreadBooks,
        ///        (SELECT COUNT([BookId]) FROM [ComicsLibrary].[SeriesAllBooks] WHERE [SeriesId] = S.[Id]) TotalBooks,
        ///        [Abandoned] [Archived]
        ///	FROM [ComicsLibrary].[Series] S
        ///		INNER JOIN [ComicsLibrary].[SeriesAllBooks] U ON U.[SeriesId] = S.[Id]
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetAllSeries_v2 {
            get {
                return ResourceManager.GetString("Create_GetAllSeries_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetBooks]
        ///    @SeriesId INT,
        ///    @TypeId INT,
        ///    @Limit INT,
        ///    @Offset INT
        ///AS
        ///BEGIN
        ///
        ///    SELECT
        ///        [Id],
        ///        [BookTypeID],
        ///        [SeriesId],
        ///        [SourceItemID],
        ///        [Title],
        ///        [Number],
        ///        [Creators],
        ///        [OnSaleDate],
        ///        [ImageUrl],
        ///        [ReadUrl],
        ///        [DateAdded],
        ///        [ReadUrlAdded],
        ///        [DateRead],
        ///        [Hidden]
        ///    FROM
        ///        [ComicsLibrary].[Books]
        ///    WHERE
        ///        [SeriesId] = @Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetBooks {
            get {
                return ResourceManager.GetString("Create_GetBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetHomeBooks]
        ///AS
        ///BEGIN
        ///
        ///	WITH [ReadableBooks] AS (
        ///		SELECT 
        ///			S.[Id] [SeriesId], 
        ///			B.[Id] [BookId],
        ///			B.[Title], 
        ///			B.[Number], 
        ///			B.[ImageUrl],
        ///			T.[Name] [BookTypeName],
        ///			T.[ID] [BookTypeID],
        ///			DENSE_RANK() OVER (PARTITION BY S.[Id] ORDER BY B.[OnSaleDate], B.[Number], B.[SourceItemID]) [Rank]
        ///		FROM [ComicsLibrary].[Series] S
        ///			INNER JOIN [ComicsLibrary].[Books] B ON B.[SeriesId] = S.[Id]
        ///				AND B.[Hidden] = 0
        ///				AND B.[DateRead] IS NULL
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetHomeBooks_v1 {
            get {
                return ResourceManager.GetString("Create_GetHomeBooks_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetHomeBooks]
        ///AS
        ///BEGIN
        ///
        ///		WITH [ReadableBooks] AS (
        ///		SELECT 
        ///			S.[Id] [SeriesId], 
        ///			B.[Id] [BookId],
        ///			B.[Title], 
        ///			B.[Number], 
        ///			B.[ImageUrl],
        ///			B.[ReadUrl],
        ///			B.[Creators],
        ///			T.[Name] [BookTypeName],
        ///			T.[ID] [BookTypeID],
        ///			DENSE_RANK() OVER (PARTITION BY S.[Id] ORDER BY B.[OnSaleDate], B.[Number], B.[SourceItemID]) [Rank]
        ///		FROM [ComicsLibrary].[Series] S
        ///			INNER JOIN [ComicsLibrary].[Books] B ON B.[SeriesId] = S.[Id]
        ///				AND B.[Hidden]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetHomeBooks_v2 {
            get {
                return ResourceManager.GetString("Create_GetHomeBooks_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetHomeBooks]
        ///	@SeriesID INT = NULL
        ///AS
        ///BEGIN
        ///
        ///		WITH [ReadableBooks] AS (
        ///		SELECT 
        ///			S.[Id] [SeriesId], 
        ///			B.[Id] [BookId],
        ///			B.[Title], 
        ///			B.[Number], 
        ///			B.[ImageUrl],
        ///			B.[ReadUrl],
        ///			B.[Creators],
        ///			T.[Name] [BookTypeName],
        ///			T.[ID] [BookTypeID],
        ///			DENSE_RANK() OVER (PARTITION BY S.[Id] ORDER BY B.[OnSaleDate], B.[Number], B.[SourceItemID]) [Rank]
        ///		FROM [ComicsLibrary].[Series] S
        ///			INNER JOIN [ComicsLibrary].[Books] B ON B.[SeriesId] = S.[I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetHomeBooks_v3 {
            get {
                return ResourceManager.GetString("Create_GetHomeBooks_v3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetHomeBooks]
        ///	@SeriesID INT = NULL
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		 B.[Id]
        ///		  ,S.[Id] SeriesId
        ///		  ,s.Title SeriesTitle
        ///		  ,CASE
        ///			WHEN b.BookTypeID = 1 THEN CONCAT(&apos;#&apos;, CAST(b.Number AS VARCHAR))
        ///			WHEN b.BookTypeID = 2 THEN CONCAT(&apos;Vol. &apos;, CAST(b.Number AS VARCHAR))
        ///			ELSE &apos;&apos;
        ///			END IssueTitle
        ///		  ,b.ImageUrl
        ///		  ,b.ReadUrl
        ///		  ,(SELECT COUNT(BookId) FROM [ComicsLibrary].[SeriesUnreadBooks] WHERE SeriesId = S.Id) UnreadIssues
        ///		  ,b.Creators
        ///	FROM [ComicsLibr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetHomeBooks_v4 {
            get {
                return ResourceManager.GetString("Create_GetHomeBooks_v4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetHomeBooks]
        ///	@SeriesID INT = NULL
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		B.[Id]
        ///		,S.[Id] SeriesId
        ///		,s.Title SeriesTitle
        ///		,CASE
        ///		WHEN b.BookTypeID = 1 THEN CONCAT(&apos;#&apos;, CAST(b.Number AS VARCHAR))
        ///		WHEN b.BookTypeID = 2 THEN CONCAT(&apos;Vol. &apos;, CAST(b.Number AS VARCHAR))
        ///		ELSE &apos;&apos;
        ///		END IssueTitle
        ///		,b.ImageUrl
        ///		,b.ReadUrl
        ///		,P.UnreadBooks
        ///		,b.Creators
        ///		,CAST(100 * CAST(P.ReadBooks AS DECIMAL) / CAST(P.TotalBooks AS DECIMAL) AS INTEGER) [Progress]
        ///	FROM [ComicsLibrary]. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetHomeBooks_v5 {
            get {
                return ResourceManager.GetString("Create_GetHomeBooks_v5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetHomeBooks]
        ///	@SeriesID INT = NULL
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		B.[Id]
        ///		,S.[Id] SeriesId
        ///		,s.Title SeriesTitle
        ///		,CASE
        ///		WHEN b.BookTypeID = 1 THEN CONCAT(&apos;#&apos;, CAST(b.Number AS VARCHAR))
        ///		WHEN b.BookTypeID = 2 THEN CONCAT(&apos;Vol. &apos;, CAST(b.Number AS VARCHAR))
        ///		ELSE &apos;&apos;
        ///		END IssueTitle
        ///		,b.ImageUrl
        ///		,b.ReadUrl
        ///		,P.UnreadBooks
        ///		,b.Creators
        ///		,CAST(100 * CAST(P.ReadBooks AS DECIMAL) / CAST(P.TotalBooks AS DECIMAL) AS INTEGER) [Progress]
        ///		,Pub.ShortName [Publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetHomeBooks_v6 {
            get {
                return ResourceManager.GetString("Create_GetHomeBooks_v6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetSeries]
        ///    @SeriesID INT = NULL
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		S.Id,
        ///        S.Title,
        ///        B.ImageUrl,
        ///        (SELECT COUNT([BookId]) FROM [ComicsLibrary].[SeriesUnreadBooks] WHERE [SeriesId] = S.[Id]) UnreadBooks,
        ///        (SELECT COUNT([BookId]) FROM [ComicsLibrary].[SeriesAllBooks] WHERE [SeriesId] = S.[Id]) TotalBooks,
        ///        [Abandoned] [Archived]
        ///	FROM [ComicsLibrary].[Series] S
        ///		INNER JOIN [ComicsLibrary].[SeriesAllBooks] U ON U.[SeriesId] = S.[Id]
        ///		INN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetSeries {
            get {
                return ResourceManager.GetString("Create_GetSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetSeries]
        ///    @SeriesID INT = NULL
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		S.Id,
        ///        S.Title,
        ///        B.ImageUrl,
        ///        P.UnreadBooks,
        ///        P.TotalBooks,
        ///        [Abandoned] [Archived],
        ///		CAST(100 * CAST(P.ReadBooks AS DECIMAL) / CAST(P.TotalBooks AS DECIMAL) AS INTEGER) [Progress]
        ///	FROM [ComicsLibrary].[Series] S
        ///		INNER JOIN [ComicsLibrary].[SeriesProgress] P ON P.[Id] = S.[Id]
        ///		INNER JOIN [ComicsLibrary].[SeriesAllBooks] U ON U.[SeriesId] = S.[Id]
        ///		INNER JOIN [C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetSeries_v2 {
            get {
                return ResourceManager.GetString("Create_GetSeries_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetSeriesByStatus]
        ///    @Status INT
        ///AS
        ///BEGIN
        ///
        ///	-- Reading = 0,
        ///	-- New = 1,
        ///	-- Finished = 2,
        ///	-- Archived = 3
        ///
        ///	SELECT 
        ///		S.Id,
        ///        S.Title,
        ///        B.ImageUrl,
        ///		CAST(100 * CAST(P.ReadBooks AS DECIMAL) / CAST(P.TotalBooks AS DECIMAL) AS INTEGER) [Progress],
        ///		S.[Abandoned] [Archived]
        ///	FROM [ComicsLibrary].[Series] S
        ///		INNER JOIN [ComicsLibrary].[SeriesProgress] P ON P.[Id] = S.[Id]
        ///		INNER JOIN [ComicsLibrary].[SeriesAllBooks] U ON U.[SeriesId] = S.[I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetSeriesByStatus {
            get {
                return ResourceManager.GetString("Create_GetSeriesByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetSeriesIds]
        ///    @SourceId INT
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		[SourceItemID] [SourceItemId],
        ///		[Id] [LibraryId]
        ///	FROM
        ///		[ComicsLibrary].[Series]
        ///	WHERE
        ///		[SourceId] = @SourceId
        ///
        ///END
        ///GO.
        /// </summary>
        internal static string Create_GetSeriesIds {
            get {
                return ResourceManager.GetString("Create_GetSeriesIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetSeriesWithBooks]
        ///    @SeriesId INT
        ///AS
        ///BEGIN
        ///    
        ///    SELECT [Id], [Title]
        ///	FROM [ComicsLibrary].[Series]
        ///	WHERE [Id] = @SeriesId
        ///
        ///	SELECT
        ///		[Id],
        ///		[ReadUrl],
        ///		[ImageUrl],
        ///		CASE WHEN [DateRead] IS NULL THEN 0 ELSE 1 END [IsRead],
        ///		[Title],
        ///		[Hidden]
        ///	FROM [ComicsLibrary].[Books]
        ///	WHERE [SeriesId] = @SeriesId
        ///
        ///	SELECT B.[Id], B.[Name]
        ///	FROM [ComicsLibrary].[HomeBookTypes] H
        ///		INNER JOIN [ComicsLibrary].[BookType] B ON B.[ID] = H.[BookTypeId]
        ///	WHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetSeriesWithBooks {
            get {
                return ResourceManager.GetString("Create_GetSeriesWithBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetSeriesWithBooks]
        ///    @SeriesId INT
        ///AS
        ///BEGIN
        ///    
        ///    SELECT [Id], [Title]
        ///	FROM [ComicsLibrary].[Series]
        ///	WHERE [Id] = @SeriesId
        ///
        ///	SELECT
        ///		[Id],
        ///		[ReadUrl],
        ///		[ImageUrl],
        ///		CASE WHEN [DateRead] IS NULL THEN 0 ELSE 1 END [IsRead],
        ///		[Title],
        ///		[Hidden],
        ///		[BookTypeID]
        ///	FROM [ComicsLibrary].[Books]
        ///	WHERE [SeriesId] = @SeriesId
        ///
        ///	SELECT B.[Id], B.[Name], H.[Enabled]
        ///	FROM [ComicsLibrary].[HomeBookTypes] H
        ///		INNER JOIN [ComicsLibrary].[BookType] B ON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetSeriesWithBooks_v2 {
            get {
                return ResourceManager.GetString("Create_GetSeriesWithBooks_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetSeriesWithBooks]
        ///    @SeriesId INT
        ///AS
        ///BEGIN
        ///    
        ///    SELECT [Id], [Title]
        ///	FROM [ComicsLibrary].[Series]
        ///	WHERE [Id] = @SeriesId
        ///
        ///	SELECT
        ///		[Id],
        ///		[ReadUrl],
        ///		[ImageUrl],
        ///		CASE WHEN [DateRead] IS NULL THEN 0 ELSE 1 END [IsRead],
        ///		[Title],
        ///		[Hidden],
        ///		[BookTypeID],
        ///		[Number]
        ///	FROM [ComicsLibrary].[Books]
        ///	WHERE [SeriesId] = @SeriesId
        ///
        ///	SELECT B.[Id], B.[Name], H.[Enabled]
        ///	FROM [ComicsLibrary].[HomeBookTypes] H
        ///		INNER JOIN [ComicsLibrary].[B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetSeriesWithBooks_v3 {
            get {
                return ResourceManager.GetString("Create_GetSeriesWithBooks_v3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[GetShelf]
        ///    @Shelf INT
        ///AS
        ///BEGIN
        ///
        ///	SELECT 
        ///		S.Id,
        ///        S.Title,
        ///        B.ImageUrl,
        ///		CAST(100 * CAST(P.ReadBooks AS DECIMAL) / CAST(P.TotalBooks AS DECIMAL) AS INTEGER) [Progress],
        ///		S.[Abandoned] [Archived]
        ///	FROM [ComicsLibrary].[Series] S
        ///		INNER JOIN [ComicsLibrary].[SeriesProgress] P ON P.[Id] = S.[Id]
        ///		INNER JOIN [ComicsLibrary].[SeriesAllBooks] U ON U.[SeriesId] = S.[Id]
        ///		INNER JOIN [ComicsLibrary].[Books] B ON B.[Id] = U.[BookId]
        ///		INNER JOIN [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_GetShelf {
            get {
                return ResourceManager.GetString("Create_GetShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[InsertSeries]
        ///    @SourceId INT,
        ///    @SourceItemID INT,
        ///    @Title NVARCHAR(255),
        ///    @Url NVARCHAR(255),
        ///    @ImageUrl NVARCHAR(255),
        ///    @Id INT OUTPUT
        ///AS
        ///BEGIN
        ///
        ///	INSERT INTO [ComicsLibrary].[Series] (
        ///        [SourceId],
        ///        [SourceItemID],
        ///        [Title],
        ///        [Url],
        ///        [ImageUrl]
        ///    )
        ///    VALUES (
        ///        @SourceId,
        ///        @SourceItemID,
        ///        @Title,
        ///        @Url,
        ///        @ImageUrl
        ///    )
        ///
        ///    SET @Id = SCOPE_IDENTITY()
        ///
        ///END        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_InsertSeries {
            get {
                return ResourceManager.GetString("Create_InsertSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[InsertSeries]
        ///    @SourceId INT,
        ///    @SourceItemID INT,
        ///    @Title NVARCHAR(255),
        ///    @Url NVARCHAR(255),
        ///    @ImageUrl NVARCHAR(255),
        ///    @Id INT OUTPUT
        ///AS
        ///BEGIN
        ///
        ///	INSERT INTO [ComicsLibrary].[Series] (
        ///        [SourceId],
        ///        [SourceItemID],
        ///        [Title],
        ///        [Url],
        ///        [ImageUrl],
        ///        [IsFinished],
        ///        [LastUpdated],
        ///        [Abandoned]
        ///    )
        ///    VALUES (
        ///        @SourceId,
        ///        @SourceItemID,
        ///        @Title,
        ///        @Url [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_InsertSeries_v2 {
            get {
                return ResourceManager.GetString("Create_InsertSeries_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[UpdateArchivedStatus]
        ///    @SeriesId INT,
        ///	@Archived BIT
        ///AS
        ///BEGIN
        ///
        ///	UPDATE [ComicsLibrary].[Series]
        ///	SET [Abandoned] = @Archived
        ///	WHERE [Id] = @SeriesId
        ///
        ///END
        ///GO.
        /// </summary>
        internal static string Create_UpdateArchivedStatus {
            get {
                return ResourceManager.GetString("Create_UpdateArchivedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[UpdateBookHideStatus]
        ///    @Id INT,
        ///    @Hide BIT
        ///AS
        ///BEGIN
        ///
        ///    UPDATE [ComicsLibrary].[Books]
        ///    SET [Hidden] = @Hide
        ///    WHERE [Id] = @Id
        ///
        ///END
        ///GO.
        /// </summary>
        internal static string Create_UpdateBookHideStatus {
            get {
                return ResourceManager.GetString("Create_UpdateBookHideStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[UpdateBookReadStatus]
        ///    @Id INT,
        ///    @Read BIT
        ///AS
        ///BEGIN
        ///
        ///    UPDATE [ComicsLibrary].[Books]
        ///    SET [DateRead] = CASE WHEN @Read = 1 THEN GETDATE() ELSE NULL END
        ///    WHERE [Id] = @Id
        ///
        ///END
        ///GO.
        /// </summary>
        internal static string Create_UpdateBookReadStatus {
            get {
                return ResourceManager.GetString("Create_UpdateBookReadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [ComicsLibrary].[UpdateHomeBookType]
        ///    @SeriesId INT,
        ///    @BookTypeId INT,
        ///    @Enabled BIT
        ///AS
        ///BEGIN
        ///
        ///    IF NOT EXISTS (
        ///		SELECT [Id] 
        ///		FROM [ComicsLibrary].[HomeBookTypes]
        ///		WHERE [SeriesId] = @SeriesId 
        ///			AND [BookTypeId] = @BookTypeId
        ///	)
        ///	BEGIN
        ///		INSERT INTO [ComicsLibrary].[HomeBookTypes] (
        ///			[SeriesId],
        ///			[BookTypeId],
        ///			[Enabled]
        ///		)
        ///		VALUES (
        ///			@SeriesId, 
        ///			@BookTypeId, 
        ///			@Enabled)
        ///	END
        ///
        ///	UPDATE [ComicsLibrary].[HomeBookTypes]
        ///	SET [Enabled] = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_UpdateHomeBookType {
            get {
                return ResourceManager.GetString("Create_UpdateHomeBookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;DeleteSeries&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[DeleteSeries]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_DeleteSeries {
            get {
                return ResourceManager.GetString("Drop_DeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetAllSeries&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetAllSeries]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetAllSeries {
            get {
                return ResourceManager.GetString("Drop_GetAllSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetBooks&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetBooks]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetBooks {
            get {
                return ResourceManager.GetString("Drop_GetBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetHomeBooks&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetHomeBooks]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetHomeBooks {
            get {
                return ResourceManager.GetString("Drop_GetHomeBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetSeries&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetSeries]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetSeries {
            get {
                return ResourceManager.GetString("Drop_GetSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetSeriesByStatus&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetSeriesByStatus]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetSeriesByStatus {
            get {
                return ResourceManager.GetString("Drop_GetSeriesByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetSeriesIds&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetSeriesIds]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetSeriesIds {
            get {
                return ResourceManager.GetString("Drop_GetSeriesIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetSeriesWithBooks&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetSeriesWithBooks]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetSeriesWithBooks {
            get {
                return ResourceManager.GetString("Drop_GetSeriesWithBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;GetShelf&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[GetShelf]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_GetShelf {
            get {
                return ResourceManager.GetString("Drop_GetShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;InsertSeries&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[InsertSeries]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_InsertSeries {
            get {
                return ResourceManager.GetString("Drop_InsertSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;UpdateArchivedStatus&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[UpdateArchivedStatus]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_UpdateArchivedStatus {
            get {
                return ResourceManager.GetString("Drop_UpdateArchivedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;UpdateBookHideStatus&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[UpdateBookHideStatus]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_UpdateBookHideStatus {
            get {
                return ResourceManager.GetString("Drop_UpdateBookHideStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;UpdateBookReadStatus&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[UpdateBookReadStatus]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_UpdateBookReadStatus {
            get {
                return ResourceManager.GetString("Drop_UpdateBookReadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id 
        ///	FROM SYS.OBJECTS O
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = O.schema_id
        ///	WHERE O.[Name] = &apos;UpdateHomeBookType&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP PROCEDURE [ComicsLibrary].[UpdateHomeBookType]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_UpdateHomeBookType {
            get {
                return ResourceManager.GetString("Drop_UpdateHomeBookType", resourceCulture);
            }
        }
    }
}
