//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsLibrary.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicsLibrary.Data.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [ComicsLibrary].[SeriesAllBooks]
        ///AS
        ///SELECT 
        ///	S.[Id] [SeriesId], 
        ///	B.[Id] [BookId],
        ///	DENSE_RANK() OVER (PARTITION BY S.[Id] ORDER BY B.[OnSaleDate], B.[Number], B.[SourceItemID]) [Rank]
        ///FROM [ComicsLibrary].[Series] S
        ///	INNER JOIN [ComicsLibrary].[Books] B ON B.[SeriesId] = S.[Id]
        ///		AND B.[Hidden] = 0
        ///	INNER JOIN [ComicsLibrary].[HomeBookTypes] H ON H.[SeriesId] = S.[Id] 
        ///		AND H.BookTypeId = B.BookTypeID
        ///		AND H.[Enabled] = 1
        ///	INNER JOIN [ComicsLibrary].[BookType] T ON T.[ID] = H.[Boo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_SeriesAllBooks {
            get {
                return ResourceManager.GetString("Create_SeriesAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [ComicsLibrary].[SeriesProgress]
        ///AS
        ///	SELECT S.[Id], COUNT(R.[BookId]) [ReadBooks], COUNT(U.[BookId]) [UnreadBooks], COUNT(A.[BookId]) [TotalBooks]
        ///	FROM [ComicsLibrary].[Series] S
        ///		INNER JOIN [ComicsLibrary].[SeriesAllBooks] A ON A.[SeriesId] = S.[Id]
        ///		LEFT JOIN [ComicsLibrary].[SeriesUnreadBooks] U ON U.[SeriesId] = S.[Id] AND A.[BookId] = U.[BookId]
        ///		LEFT JOIN [ComicsLibrary].[SeriesReadBooks] R ON R.[SeriesId] = S.[Id] AND A.[BookId] = R.[BookId]
        ///	WHERE [Id] = 1
        ///	GROUP BY S.[Id]
        ///G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_SeriesProgress {
            get {
                return ResourceManager.GetString("Create_SeriesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [ComicsLibrary].[SeriesProgress]
        ///AS
        ///	SELECT S.[Id], COUNT(R.[BookId]) [ReadBooks], COUNT(U.[BookId]) [UnreadBooks], COUNT(A.[BookId]) [TotalBooks]
        ///	FROM [ComicsLibrary].[Series] S
        ///		INNER JOIN [ComicsLibrary].[SeriesAllBooks] A ON A.[SeriesId] = S.[Id]
        ///		LEFT JOIN [ComicsLibrary].[SeriesUnreadBooks] U ON U.[SeriesId] = S.[Id] AND A.[BookId] = U.[BookId]
        ///		LEFT JOIN [ComicsLibrary].[SeriesReadBooks] R ON R.[SeriesId] = S.[Id] AND A.[BookId] = R.[BookId]
        ///	GROUP BY S.[Id]
        ///GO.
        /// </summary>
        internal static string Create_SeriesProgress_v2 {
            get {
                return ResourceManager.GetString("Create_SeriesProgress_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [ComicsLibrary].[SeriesReadBooks]
        ///AS
        ///SELECT 
        ///	S.[Id] [SeriesId], 
        ///	B.[Id] [BookId],
        ///	DENSE_RANK() OVER (PARTITION BY S.[Id] ORDER BY B.[OnSaleDate], B.[Number], B.[SourceItemID]) [Rank]
        ///FROM [ComicsLibrary].[Series] S
        ///	INNER JOIN [ComicsLibrary].[Books] B ON B.[SeriesId] = S.[Id]
        ///		AND B.[Hidden] = 0
        ///		AND B.[DateRead] IS NOT NULL
        ///	INNER JOIN [ComicsLibrary].[HomeBookTypes] H ON H.[SeriesId] = S.[Id] 
        ///		AND H.BookTypeId = B.BookTypeID
        ///		AND H.[Enabled] = 1
        ///	INNER JOIN [ComicsLibrary [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_SeriesReadBooks {
            get {
                return ResourceManager.GetString("Create_SeriesReadBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [ComicsLibrary].[SeriesUnreadBooks]
        ///AS
        ///SELECT 
        ///	S.[Id] [SeriesId], 
        ///	B.[Id] [BookId],
        ///	DENSE_RANK() OVER (PARTITION BY S.[Id] ORDER BY B.[OnSaleDate], B.[Number], B.[SourceItemID]) [Rank]
        ///FROM [ComicsLibrary].[Series] S
        ///	INNER JOIN [ComicsLibrary].[Books] B ON B.[SeriesId] = S.[Id]
        ///		AND B.[Hidden] = 0
        ///		AND B.[DateRead] IS NULL
        ///	INNER JOIN [ComicsLibrary].[HomeBookTypes] H ON H.[SeriesId] = S.[Id] 
        ///		AND H.BookTypeId = B.BookTypeID
        ///		AND H.[Enabled] = 1
        ///	INNER JOIN [ComicsLibrary]. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_SeriesUnreadBooks {
            get {
                return ResourceManager.GetString("Create_SeriesUnreadBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id
        ///	FROM SYS.VIEWS V
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = V.schema_id
        ///	WHERE V.[Name] = &apos;SeriesAllBooks&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP VIEW [ComicsLibrary].[SeriesAllBooks]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_SeriesAllBooks {
            get {
                return ResourceManager.GetString("Drop_SeriesAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id
        ///	FROM SYS.VIEWS V
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = V.schema_id
        ///	WHERE V.[Name] = &apos;SeriesProgress&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP VIEW [ComicsLibrary].[SeriesProgress]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_SeriesProgress {
            get {
                return ResourceManager.GetString("Drop_SeriesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id
        ///	FROM SYS.VIEWS V
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = V.schema_id
        ///	WHERE V.[Name] = &apos;SeriesReadBooks&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP VIEW [ComicsLibrary].[SeriesReadBooks]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_SeriesReadBooks {
            get {
                return ResourceManager.GetString("Drop_SeriesReadBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///	SELECT object_id
        ///	FROM SYS.VIEWS V
        ///		INNER JOIN SYS.SCHEMAS S ON S.schema_id = V.schema_id
        ///	WHERE V.[Name] = &apos;SeriesUnreadBooks&apos;
        ///		AND S.[Name] = &apos;ComicsLibrary&apos;
        ///)
        ///BEGIN
        ///	DROP VIEW [ComicsLibrary].[SeriesUnreadBooks]
        ///END
        ///GO.
        /// </summary>
        internal static string Drop_SeriesUnreadBooks {
            get {
                return ResourceManager.GetString("Drop_SeriesUnreadBooks", resourceCulture);
            }
        }
    }
}
